
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yasser Dalal
 */
public class Calculator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculator.class.getName());

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FirstNumberField = new javax.swing.JTextField();
        SecondNumberField = new javax.swing.JTextField();
        Result = new javax.swing.JLabel();
        Subtract = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        Quit = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("First Number:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Second Number:");

        FirstNumberField.setBackground(new java.awt.Color(255, 255, 255));
        FirstNumberField.setForeground(new java.awt.Color(0, 0, 0));
        FirstNumberField.setCaretColor(new java.awt.Color(0, 0, 0));
        FirstNumberField.addActionListener(this::FirstNumberFieldActionPerformed);

        SecondNumberField.setBackground(new java.awt.Color(255, 255, 255));
        SecondNumberField.setForeground(new java.awt.Color(0, 0, 0));
        SecondNumberField.addActionListener(this::SecondNumberFieldActionPerformed);

        Result.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Result.setText("Result:");

        Subtract.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Subtract.setText("SUBTRACT");
        Subtract.addActionListener(this::SubtractActionPerformed);

        Divide.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Divide.setText("DIVIDE");
        Divide.addActionListener(this::DivideActionPerformed);

        Quit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Quit.setText("QUIT");
        Quit.addActionListener(this::QuitActionPerformed);

        Add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(this::AddActionPerformed);

        Multiply.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Multiply.setText("MULTIPLY");
        Multiply.addActionListener(this::MultiplyActionPerformed);

        Reset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Reset.setText("RESET");
        Reset.addActionListener(this::ResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SecondNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Subtract, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Quit, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(FirstNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Result))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FirstNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addComponent(Result)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Divide)
                            .addComponent(Multiply))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quit)
                            .addComponent(Reset)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Add)
                        .addComponent(Subtract)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNumberFieldActionPerformed
        // TODO add your handling code here:
            
    }//GEN-LAST:event_FirstNumberFieldActionPerformed

    private void SecondNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondNumberFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SecondNumberFieldActionPerformed

    private void SubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubtractActionPerformed
        // TODO add your handling code here:
        if(FirstNumberField.getText().equals("") || SecondNumberField.getText().equals("")){
            if(FirstNumberField.getText().equals("") && SecondNumberField.getText().equals("")){
                Result.setText("Result: Both field must not be empty");
                return;
            }
            if(FirstNumberField.getText().equals("")){
                Result.setText("Result: First Number must not be empty");
                return;
            }
            if(SecondNumberField.getText().equals("")){
                Result.setText("Result: Second Number must not be empty");
                return;
            }
        }
        try {
            double num1 = Double.parseDouble(FirstNumberField.getText());
            double num2 = Double.parseDouble(SecondNumberField.getText());
            
            Result.setText("Result: " + (num1 - num2));
        } catch(NumberFormatException e){
            Result.setText("Result: Both field must be numbers");
        }
            
    }//GEN-LAST:event_SubtractActionPerformed

    private void DivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivideActionPerformed
        // TODO add your handling code here:
        if(FirstNumberField.getText().equals("") || SecondNumberField.getText().equals("")){
            if(FirstNumberField.getText().equals("") && SecondNumberField.getText().equals("")){
                Result.setText("Result: Both field must not be empty");
                return;
            }
            if(FirstNumberField.getText().equals("")){
                Result.setText("Result: First Number must not be empty");
                return;
            }
            if(SecondNumberField.getText().equals("")){
                Result.setText("Result: Second Number must not be empty");
                return;
            }
        }
        try {
            double num1 = Double.parseDouble(FirstNumberField.getText());
            double num2 = Double.parseDouble(SecondNumberField.getText());
            
            Result.setText("Result: " + (num1 / num2));
        } catch(NumberFormatException e){
            Result.setText("Result: Both field must be numbers");
        }
    }//GEN-LAST:event_DivideActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        Object[] option = {"OK"};
        int choice = JOptionPane.showOptionDialog(
            this,
            "This will terminate the program!",
            "Exit",
            JOptionPane.OK_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            option,
            option[0]
        );
        
        if (choice == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_QuitActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        if(FirstNumberField.getText().equals("") || SecondNumberField.getText().equals("")){
            if(FirstNumberField.getText().equals("") && SecondNumberField.getText().equals("")){
                Result.setText("Result: Both field must not be empty");
                return;
            }
            if(FirstNumberField.getText().equals("")){
                Result.setText("Result: First Number must not be empty");
                return;
            }
            if(SecondNumberField.getText().equals("")){
                Result.setText("Result: Second Number must not be empty");
                return;
            }
        }
        try {
            double num1 = Double.parseDouble(FirstNumberField.getText());
            double num2 = Double.parseDouble(SecondNumberField.getText());
            
            Result.setText("Result: " + (num1 + num2));
        } catch(NumberFormatException e){
            Result.setText("Result: Both field must be numbers");
        }
    }//GEN-LAST:event_AddActionPerformed

    private void MultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplyActionPerformed
        // TODO add your handling code here:
        if(FirstNumberField.getText().equals("") || SecondNumberField.getText().equals("")){
            if(FirstNumberField.getText().equals("") && SecondNumberField.getText().equals("")){
                Result.setText("Result: Both field must not be empty");
                return;
            }
            if(FirstNumberField.getText().equals("")){
                Result.setText("Result: First Number must not be empty");
                return;
            }
            if(SecondNumberField.getText().equals("")){
                Result.setText("Result: Second Number must not be empty");
                return;
            }
        }
        try {
            double num1 = Double.parseDouble(FirstNumberField.getText());
            double num2 = Double.parseDouble(SecondNumberField.getText());
            
            Result.setText("Result: " + (num1 * num2));
        } catch(NumberFormatException e){
            Result.setText("Result: Both field must be numbers");
        }
    }//GEN-LAST:event_MultiplyActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        
        FirstNumberField.setText(""); 
        SecondNumberField.setText("");
        Result.setText("Result: ");
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Divide;
    private javax.swing.JTextField FirstNumberField;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton Quit;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Result;
    private javax.swing.JTextField SecondNumberField;
    private javax.swing.JButton Subtract;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
